version: "3.9"

services:

  backend:
    build: ./ToDo_DRF
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ToDo_DRF:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
